import { FormEvent, useEffect, useMemo, useState } from 'react';
import { adminRequest } from './pairing';
import { canSubmitGoldImport, canSubmitPaidGoldCreation, paidGoldCreditWarning, resolveGoldImportRequest, resolveGoldPackageState, resolvePaidGoldCreationRequest, type GoldAccountType } from './adminGoldPanelState';
import { classifyGoldExpiration, EXPIRATION_BUCKETS, EXPIRATION_BUCKET_LABELS, sortGoldAccountsByExpiration, type ExpirationBucket } from './goldOperations';

type Row = Record<string, any>;
type Props = { token: string; devices: Row[]; providers: Row[]; onAssignProvider: (deviceId: string, providerId: string) => void; onMessage: (message: string) => void; openCreate?: boolean; onOpenCreateHandled?: () => void };
const SUBSCRIPTIONS = [['1', '1 Month'], ['3', '3 Months'], ['6', '6 Months'], ['12', '12 Months']];
const ACCOUNT_TYPES: Array<[GoldAccountType, string]> = [['import', 'Import Gold Demo'], ['paid', 'Paid Account']];
const ACTION_LABELS: Record<string, string> = { account_created: 'Account created', account_imported: 'Demo imported', account_synced: 'Account synced', account_renewed: 'Account renewed', account_enabled: 'Account enabled', account_disabled: 'Account disabled', diagnostics_run: 'Diagnostics run', recovery_completed: 'Recovery completed', credentials_accessed: 'Credentials accessed', provider_assigned: 'Provider assigned' };

export function AdminGoldPanel({ token, providers, onAssignProvider, onMessage, openCreate, onOpenCreateHandled }: Props) {
  const [accounts, setAccounts] = useState<Row[]>([]); const [reseller, setReseller] = useState<Row | null>(null); const [packages, setPackages] = useState<Row[]>([]); const [activity, setActivity] = useState<Row[]>([]); const [activityUnavailable, setActivityUnavailable] = useState(false); const [packageEmptyReason, setPackageEmptyReason] = useState('');
  const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [selected, setSelected] = useState<Row | null>(null); const [recovery, setRecovery] = useState<Row | null>(null); const [busy, setBusy] = useState(false); const [expirationFilter, setExpirationFilter] = useState<ExpirationBucket | null>(null);
  const [form, setForm] = useState({ accountType: 'import' as GoldAccountType, m3uUrl: '', sub: '1', packageId: '', country: 'US', notes: '', displayName: '', runDiagnostics: true, activateIfHealthy: false });
  const load = async () => { setLoading(true); try { const [list, resellerResult, packageResult, activityResult] = await Promise.all([adminRequest('admin-gold-panel', token), adminRequest('admin-gold-panel', token, { method: 'POST', body: JSON.stringify({ action: 'reseller' }) }), adminRequest('admin-gold-panel', token, { method: 'POST', body: JSON.stringify({ action: 'packages' }) }), adminRequest('admin-gold-panel', token, { method: 'POST', body: JSON.stringify({ action: 'activity' }) }).catch(() => ({ activity: [], unavailable: true }))]); const packageState = resolveGoldPackageState(packageResult); setAccounts(Array.isArray(list.accounts) ? list.accounts : []); setReseller(resellerResult.reseller ?? null); setPackages(packageState.packages); setPackageEmptyReason(packageState.emptyReason); setActivity(Array.isArray(activityResult.activity) ? activityResult.activity : []); setActivityUnavailable(activityResult.unavailable === true); if (!packageState.packages.length) setForm((current) => current.accountType === 'paid' ? { ...current, packageId: '' } : current); } catch (error) { onMessage(`Gold Panel could not refresh (${error instanceof Error ? error.message : 'request failed'}).`); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [token]); useEffect(() => { if (openCreate) { setModal(true); onOpenCreateHandled?.(); } }, [openCreate, onOpenCreateHandled]);
  const providerById = useMemo(() => new Map(providers.map((provider) => [String(provider.id), provider])), [providers]);
  const bucketCounts = useMemo(() => Object.fromEntries(EXPIRATION_BUCKETS.map((bucket) => [bucket, accounts.filter((account) => classifyGoldExpiration(account.gold_expiration) === bucket).length])), [accounts]);
  const visibleAccounts = useMemo(() => sortGoldAccountsByExpiration(expirationFilter ? accounts.filter((account) => classifyGoldExpiration(account.gold_expiration) === expirationFilter) : accounts), [accounts, expirationFilter]);
  const expiring = (bucketCounts.today ?? 0) + (bucketCounts.tomorrow ?? 0) + (bucketCounts.next7 ?? 0); const routeAlerts = accounts.filter((account) => account.route_health?.reachable === false).length; const canSubmit = form.accountType === 'import' ? canSubmitGoldImport(form.m3uUrl) : canSubmitPaidGoldCreation(packages, form.packageId, form.sub);
  const create = async (event: FormEvent) => { event.preventDefault(); if (busy || !canSubmit) return; const warning = paidGoldCreditWarning(form.accountType); if (warning && !window.confirm(warning)) return; setBusy(true); try { const body = form.accountType === 'import' ? resolveGoldImportRequest(form) : resolvePaidGoldCreationRequest(form); const result = await adminRequest('admin-gold-panel', token, { method: 'POST', body: JSON.stringify(body) }); setModal(false); onMessage(result.summary ? 'Gold account imported and NovaCast diagnostics completed.' : form.accountType === 'import' ? 'Gold demo imported as a NovaCast draft provider.' : 'Gold account created as a NovaCast draft provider.'); await load(); } catch (error) { const payload = (error as Error & { payload?: Row }).payload; if (payload?.recoveryRequired && payload.recoveryReference) { setRecovery(payload); onMessage(payload.goldImported ? 'Gold account was imported, but NovaCast provider creation failed.' : 'Gold account created successfully. NovaCast provider creation failed.'); } else onMessage(`${form.accountType === 'import' ? 'Gold demo could not be imported' : 'Gold account could not be created'} (${error instanceof Error ? error.message : 'request failed'}).`); } finally { setBusy(false); } };
  const action = async (body: Row, message: string) => { if (busy) return; setBusy(true); try { await adminRequest('admin-gold-panel', token, { method: 'POST', body: JSON.stringify(body) }); onMessage(message); await load(); } catch (error) { onMessage(`Gold operation failed (${error instanceof Error ? error.message : 'request failed'}).`); } finally { setBusy(false); } };
  const retryRecovery = async () => { if (!recovery || busy) return; setBusy(true); try { await adminRequest('admin-gold-panel', token, { method: 'POST', body: JSON.stringify({ action: 'retry_recovery', recoveryReference: recovery.recoveryReference }) }); setRecovery(null); onMessage('NovaCast provider setup completed from the existing Gold account.'); await load(); } catch (error) { onMessage(`NovaCast recovery failed (${error instanceof Error ? error.message : 'request failed'}).`); } finally { setBusy(false); } };
  const copyCredentials = async (account: Row) => { if (!window.confirm('Reveal and copy these credentials to the clipboard?')) return; try { const result = await adminRequest('admin-gold-panel', token, { method: 'POST', body: JSON.stringify({ action: 'account_credentials', accountId: account.id }) }); await navigator.clipboard?.writeText(`Server: ${result.baseUrl}\nUsername: ${result.username}\nPassword: ${result.password}`); onMessage('Credentials copied.'); } catch { onMessage('Credentials could not be copied.'); } };
  const assign = (account: Row) => { const providerId = String(account.managed_provider_id ?? ''); const deviceId = window.prompt('Enter the NovaCast device UUID to assign this account to:'); if (deviceId && providerId) onAssignProvider(deviceId.trim(), providerId); };
  return <div className="providersPage"><section className="inviteHero"><div className="inviteHeroCopy"><div className="inviteIcon">G</div><div><h2>Gold Panel</h2><p>Provision reseller M3U accounts and manage their NovaCast provider links.</p><p>Gold, Xtream, stream, route, and NovaCast health remain separate signals.</p></div></div><div className="inviteHeroMetrics"><Metric label="RESELLER CREDITS" value={reseller?.credits ?? '—'} detail={reseller?.enabled === false ? 'Disabled' : 'Gold connection'} tone={reseller?.enabled === false ? 'red' : 'blue'} /><Metric label="MANAGED ACCOUNTS" value={accounts.length} detail="Gold-linked providers" /><Metric label="EXPIRING SOON" value={expiring} detail="Next 7 days" tone={expiring ? 'amber' : 'blue'} /><Metric label="ROUTE ALERTS" value={routeAlerts} detail="Cloud checks" tone={routeAlerts ? 'red' : 'blue'} /></div></section>
    <section className="goldExpirationCenter"><header><div><span className="eyebrow">EXPIRATION CENTER</span><small>{expirationFilter ? `Showing ${visibleAccounts.length} of ${accounts.length} Gold accounts — ${EXPIRATION_BUCKET_LABELS[expirationFilter]}` : 'Select a bucket to filter Gold accounts.'}</small></div><button className={expirationFilter === null ? 'selected' : ''} onClick={() => setExpirationFilter(null)}>All accounts <b>{accounts.length}</b></button></header><div className="goldExpirationBuckets">{EXPIRATION_BUCKETS.map((bucket) => <button key={bucket} className={`goldExpirationBucket bucket-${bucket} ${expirationFilter === bucket ? 'selected' : ''}`} onClick={() => setExpirationFilter(bucket)}><span>{EXPIRATION_BUCKET_LABELS[bucket]}</span><strong>{bucketCounts[bucket] ?? 0}</strong></button>)}</div></section>
    <section className="inviteFilters"><button className="filterButton" onClick={() => void load()} disabled={loading}>Refresh</button><button className="cloudPrimary" onClick={() => setModal(true)}>Add Gold Account</button></section>{packageEmptyReason === 'no_custom_bouquets' ? <section className="inviteEmpty"><strong>No custom bouquets configured</strong><small>Paid API provisioning requires a custom bouquet. Gold demos can still be imported using a generated M3U URL.</small></section> : null}
    {loading ? <div className="cloudLoading">Loading Gold Panel</div> : visibleAccounts.length ? <div className="providerCardGrid">{visibleAccounts.map((account) => <AccountCard key={account.id} account={account} provider={providerById.get(String(account.managed_provider_id))} busy={busy} onSync={() => void action({ action: 'sync_account', accountId: account.id }, 'Gold account synced.')} onView={() => setSelected(account)} onDiagnostics={() => void action({ action: 'run_diagnostics', accountId: account.id }, 'Gold provider diagnostics completed.')} onRenew={() => void action({ action: 'renew_account', accountId: account.id, sub: '1' }, 'Gold account renewed for 1 month.')} onToggle={() => void action({ action: 'set_account_status', accountId: account.id, enabled: account.gold_enabled === false }, account.gold_enabled === false ? 'Gold account enabled.' : 'Gold account disabled.')} onAssign={() => assign(account)} onCredentials={() => void copyCredentials(account)} />)}</div> : <section className="inviteEmpty"><div>G</div><strong>{expirationFilter ? 'No accounts in this bucket' : 'No Gold accounts yet'}</strong><small>{expirationFilter ? 'Choose another expiration bucket or view all accounts.' : 'Import a Gold demo or create a paid Gold account to provision a NovaCast provider.'}</small>{!expirationFilter ? <button onClick={() => setModal(true)}>Add Gold Account</button> : null}</section>}
    <ActivityFeed activity={activity} unavailable={activityUnavailable} />
    {modal ? <Modal title="Add Gold account" onClose={() => setModal(false)}><p>{form.accountType === 'import' ? 'Create the demo in the Gold reseller panel, then paste the generated M3U URL here.' : 'Create a paid Gold account using a documented subscription and a returned custom bouquet.'}</p><form onSubmit={create}><label>Account Type<select value={form.accountType} onChange={(e) => setForm({ ...form, accountType: e.target.value as GoldAccountType, m3uUrl: '', sub: '1', packageId: '' })}>{ACCOUNT_TYPES.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label>{form.accountType === 'import' ? <label>M3U URL<input required value={form.m3uUrl} onChange={(e) => setForm({ ...form, m3uUrl: e.target.value })} placeholder="https://server/get.php?..." /></label> : <><label>Subscription<select value={form.sub} onChange={(e) => setForm({ ...form, sub: e.target.value })}>{SUBSCRIPTIONS.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Package<select required disabled={!packages.length} value={form.packageId} onChange={(e) => setForm({ ...form, packageId: e.target.value })}>{packages.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><small>This will use Gold reseller credits.</small></>}<label>Display name<input value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} /></label><label>Notes<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><label><input type="checkbox" checked={form.runDiagnostics} onChange={(e) => setForm({ ...form, runDiagnostics: e.target.checked })} /> Run diagnostics after {form.accountType === 'import' ? 'import' : 'creation'}</label><label><input type="checkbox" checked={form.activateIfHealthy} onChange={(e) => setForm({ ...form, activateIfHealthy: e.target.checked })} /> Activate only if diagnostics pass</label><div className="modalActions"><button type="button" className="ghost" onClick={() => setModal(false)}>Cancel</button><button className="submit" disabled={busy || !canSubmit}>{busy ? 'Working…' : form.accountType === 'import' ? 'Import Gold Demo' : 'Create Paid Account'}</button></div></form></Modal> : null}
    {recovery ? <Modal title={recovery.goldImported ? 'Gold account was imported.' : 'Gold account created successfully.'}><p>NovaCast provider creation failed. The encrypted Gold credentials are retained temporarily on the server.</p><div className="modalActions"><button className="ghost" disabled={busy} onClick={() => setRecovery(null)}>Dismiss</button><button className="submit" disabled={busy} onClick={() => void retryRecovery()}>{busy ? 'Retrying…' : 'Retry NovaCast Setup'}</button></div></Modal> : null}
    {selected ? <Modal title={String(selected.gold_user_id)} onClose={() => setSelected(null)}><dl><div><span>Status</span><strong>{selected.gold_enabled === false ? 'DISABLED' : 'ACTIVE'}</strong></div><div><span>Expiration</span><strong>{selected.gold_expiration ?? 'Unknown'}</strong></div><div><span>Country</span><strong>{selected.gold_country === 'ALL' ? 'ALL — VPN / All Countries' : selected.gold_country ?? 'Unknown'}</strong></div><div><span>Package</span><strong>{selected.gold_package_name ?? selected.gold_package_id ?? 'Unknown'}</strong></div><div><span>Last sync</span><strong>{selected.last_synced_at ? new Date(selected.last_synced_at).toLocaleString() : 'Never'}</strong></div></dl><div className="modalActions"><button className="ghost" onClick={() => setSelected(null)}>Close</button><button onClick={() => void action({ action: 'sync_account', accountId: selected.id }, 'Gold account synced.')}>Sync</button></div></Modal> : null}
  </div>;
}

function AccountCard({ account, provider, busy, onSync, onView, onDiagnostics, onRenew, onToggle, onAssign, onCredentials }: any) { const bucket = classifyGoldExpiration(account.gold_expiration); const expiration = String(account.gold_expiration ?? 'Unknown'); return <article className="providerCard"><header><div><strong>{provider?.display_name ?? `Gold ${account.gold_user_id}`}</strong><small>Gold user {account.gold_user_id}</small></div><b className={`providerBadge badge-${account.gold_enabled === false ? 'disabled' : bucket === 'expired' ? 'expired' : 'active'}`}>{account.gold_enabled === false ? 'DISABLED' : bucket === 'expired' ? 'EXPIRED' : 'ACTIVE'}</b></header><dl><div><span>Package</span><strong>{account.gold_package_name ?? account.gold_package_id ?? 'Unknown'}</strong></div><div><span>Country</span><strong>{account.gold_country === 'ALL' ? 'ALL — VPN / All Countries' : account.gold_country ?? 'Unknown'}</strong></div><div><span>Expiration</span><strong>{expiration}</strong></div><div><span>Route</span><strong>{account.route_mode ?? account.route_domain ?? 'Not configured'}</strong></div></dl><p>NovaCast provider: {provider?.status ?? 'unknown'} · Health: {provider?.health_status ?? 'unvalidated'}</p><p>Assigned device: {account.assignedDevice?.public_device_code ?? 'None'}</p><footer><button disabled={busy} onClick={onSync}>Sync</button><button disabled={busy} onClick={onView}>View</button><button disabled={busy} onClick={onDiagnostics}>Run Diagnostics</button><button disabled={busy} onClick={onRenew}>Renew</button><button disabled={busy} onClick={onToggle}>{account.gold_enabled === false ? 'Enable' : 'Disable'}</button><button disabled={busy} onClick={onAssign}>Assign / Reassign</button><button disabled={busy} onClick={onCredentials}>Copy Credentials</button></footer></article>; }
function ActivityFeed({ activity, unavailable }: { activity: Row[]; unavailable: boolean }) { return <section className="goldActivity"><header><div><span className="eyebrow">RECENT GOLD ACTIVITY</span><small>Formal admin events only. No timestamp inference.</small></div></header>{unavailable ? <p className="goldActivityEmpty">Gold activity history is not available yet.</p> : activity.length ? <div className="goldActivityList">{activity.slice(0, 10).map((event) => <article key={event.id}><i /><div><strong>{(ACTION_LABELS[event.action] ?? event.action).toUpperCase()}</strong><small>{event.providerName ?? (event.goldUserId ? `Gold ${event.goldUserId}` : 'Gold account')} · {new Date(event.createdAt).toLocaleString()}</small>{event.metadata?.subscriptionMonths ? <small>{event.metadata.subscriptionMonths} month{event.metadata.subscriptionMonths === 1 ? '' : 's'}</small> : null}</div><b className={`activityStatus ${event.status === 'success' ? 'success' : 'failure'}`}>{String(event.status ?? 'success').toUpperCase()}</b></article>)}</div> : <p className="goldActivityEmpty">No Gold activity recorded yet.</p>}</section>; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose?: () => void }) { return <div className="modalBackdrop" role="presentation"><section className="inviteModal providerModal" role="dialog" aria-modal="true">{onClose ? <button className="modalClose" aria-label="Close" onClick={onClose}>×</button> : null}<span className="eyebrow">NOVACAST CLOUD ADMIN</span><h2>{title}</h2>{children}</section></div>; }
function Metric({ label, value, detail, tone = 'blue' }: { label: string; value: any; detail: string; tone?: string }) { return <div className={`inviteMetric tone-${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small><i /></div>; }
