import { useEffect, useMemo, useState, type FormEvent } from 'react';

type Row = Record<string, unknown>;
type InvitationInput = { label: string; maximumDevices: number; durationHours: number; managedProviderId: string };

export function AdminInvitations({ invitations, providers, onCreate, onMessage, openCreate, onOpenCreateHandled }: { invitations: Row[]; providers: Row[]; onCreate: (input: InvitationInput) => Promise<string>; onMessage: (message: string) => void; openCreate: boolean; onOpenCreateHandled: () => void }) {
  const [modalOpen, setModalOpen] = useState(false);
  const [lastCode, setLastCode] = useState('');
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('all');
  const [provider, setProvider] = useState('all');
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [creating, setCreating] = useState(false);
  const [label, setLabel] = useState('');
  const [maximumDevices, setMaximumDevices] = useState('1');
  const [durationHours, setDurationHours] = useState('72');
  const [managedProviderId, setManagedProviderId] = useState('');
  const assignableProviders = useMemo(() => providers.filter((item) => String(item.status ?? '') === 'active'), [providers]);
  const filtered = useMemo(() => invitations.filter((invite) => {
    const text = `${String(invite.display_label ?? '')} ${String(invite.id ?? '')}`.toLowerCase();
    return (!query.trim() || text.includes(query.trim().toLowerCase())) && (status === 'all' || invitationStatus(invite) === status) && (provider === 'all' || String(invite.managed_provider_id ?? '') === provider);
  }), [invitations, query, status, provider]);
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  const active = invitations.filter((invite) => invitationStatus(invite) === 'active').length;
  const redeemed = invitations.filter((invite) => Number(invite.redeemed_count ?? 0) > 0).length;

  useEffect(() => { if (page > pages) setPage(pages); }, [page, pages]);
  useEffect(() => { if (openCreate) { setModalOpen(true); onOpenCreateHandled(); } }, [onOpenCreateHandled, openCreate]);
  const resetFilters = () => { setQuery(''); setStatus('all'); setProvider('all'); setPage(1); };
  const copyCode = async (code: string) => { try { await navigator.clipboard.writeText(code); onMessage('Invitation code copied.'); } catch { onMessage('Copy failed. Select the code and copy it manually.'); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!managedProviderId) return onMessage('Select a managed provider before creating an invitation.'); setCreating(true); try { const code = await onCreate({ label, maximumDevices: Number(maximumDevices), durationHours: Number(durationHours), managedProviderId }); setLastCode(code); setModalOpen(false); setLabel(''); setMaximumDevices('1'); setDurationHours('72'); setManagedProviderId(''); } catch { onMessage('Could not create invitation.'); } finally { setCreating(false); } };

  return <div className="invitationsPage">
    <section className="inviteHero"><div className="inviteHeroCopy"><div className="inviteIcon"></div><div><h2>Invite &amp; Collaborate</h2><p>Create invitation codes for beta testers or managed devices.</p><p>Control provider access, device limits, and invitation duration.</p></div></div><div className="inviteHeroMetrics"><MiniMetric label="TOTAL INVITATIONS" value={invitations.length} detail="All time" tone="blue" /><MiniMetric label="ACTIVE INVITATIONS" value={active} detail="Awaiting redemption" tone="green" /><MiniMetric label="REDEEMED" value={redeemed} detail="Used at least once" tone="purple" /></div></section>
    {lastCode ? <section className="inviteSuccess"><div><span className="eyebrow">NEW INVITATION CODE</span><strong>{lastCode}</strong><small>This code can only be viewed once. Copy and store it securely.</small></div><div><button onClick={() => void copyCode(lastCode)}>Copy code</button><button className="ghost" onClick={() => setLastCode('')}>Dismiss</button></div></section> : null}
    <section className="inviteFilters"><label className="inviteSearch"><span></span><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search by label or invitation code" /></label><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} aria-label="Filter invitations by status"><option value="all">All statuses</option><option value="active">Active</option><option value="redeemed">Redeemed</option><option value="expired">Expired</option><option value="exhausted">Exhausted</option><option value="inactive">Inactive</option></select><select value={provider} onChange={(event) => { setProvider(event.target.value); setPage(1); }} aria-label="Filter invitations by provider"><option value="all">All providers</option>{providers.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.display_name ?? item.slug)}</option>)}</select><select aria-label="Filter invitations by creator" disabled><option>All users</option></select><select aria-label="Filter invitations by date" disabled><option> All time</option></select><button className="filterButton" onClick={resetFilters}>Clear filters</button></section>
    <section className="inviteTable"><div className="inviteTableHead"><span>Invitation</span><span>Label</span><span>Managed provider</span><span>Created by</span><span>Status</span><span>Uses</span><span>Expires</span><span>Created</span><span>Actions</span></div>{visible.length ? visible.map((invite) => <InvitationRow key={String(invite.id)} invite={invite} providers={providers} onMessage={onMessage} />) : <div className="inviteEmpty"><div></div><strong>{invitations.length ? 'No invitations match your filters.' : 'No invitations found'}</strong><small>Create an invitation to give a beta tester or device access.</small><button onClick={() => invitations.length ? resetFilters() : setModalOpen(true)}>{invitations.length ? 'Clear filters' : 'Create invitation'}</button></div>}<footer className="invitePagination"><span>Showing {filtered.length ? (page - 1) * pageSize + 1 : 0} to {Math.min(page * pageSize, filtered.length)} of {filtered.length} invitations</span><div><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}></button><strong>{page}</strong><button disabled={page >= pages} onClick={() => setPage((value) => value + 1)}></button></div><select value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }} aria-label="Invitations per page"><option value="10">10 / page</option><option value="25">25 / page</option><option value="50">50 / page</option></select></footer></section>
    {modalOpen ? <div className="modalBackdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setModalOpen(false); }}><section className="inviteModal" role="dialog" aria-modal="true" aria-labelledby="new-invite-title"><button className="modalClose" aria-label="Close new invitation" onClick={() => setModalOpen(false)}></button><span className="eyebrow">NOVACAST CLOUD ADMIN</span><h2 id="new-invite-title">New invitation</h2><p>Create a one-time code for a beta tester or managed device.</p><form onSubmit={submit}><label>Invitation label<input autoFocus value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Living Room TV" /></label><label>Maximum devices<select value={maximumDevices} onChange={(event) => setMaximumDevices(event.target.value)}><option value="1">1 device</option><option value="2">2 devices</option><option value="3">3 devices</option><option value="5">5 devices</option></select></label><label>Access duration<select value={durationHours} onChange={(event) => setDurationHours(event.target.value)}><option value="24">24 hours</option><option value="48">48 hours</option><option value="72">72 hours</option><option value="168">7 days</option></select></label><label>Managed provider<select required value={managedProviderId} onChange={(event) => setManagedProviderId(event.target.value)}><option value="">Select a provider</option>{assignableProviders.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.display_name ?? item.slug)}</option>)}</select></label><div className="modalActions"><button type="button" className="ghost" onClick={() => setModalOpen(false)}>Cancel</button><button className="submit" disabled={creating}>{creating ? 'Creating' : 'Create invitation'}</button></div></form></section></div> : null}
  </div>;
}

function MiniMetric({ label, value, detail, tone }: { label: string; value: number; detail: string; tone: string }) { return <div className={`inviteMetric tone-${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small><i /></div>; }
function InvitationRow({ invite, providers, onMessage }: { invite: Row; providers: Row[]; onMessage: (message: string) => void }) { const provider = providers.find((item) => String(item.id) === String(invite.managed_provider_id)); const current = invitationStatus(invite); const used = Number(invite.redeemed_count ?? 0); const max = Number(invite.maximum_devices ?? 0); const created = String(invite.created_at ?? ''); const expires = invite.expires_at ? String(invite.expires_at) : ''; const label = String(invite.display_label ?? 'Untitled invitation'); return <div className="inviteTableRow"><div><span className="hiddenCode">Code hidden</span><small>#{String(invite.id ?? '').slice(0, 8)}</small></div><strong>{label}</strong><span>{String(provider?.display_name ?? 'Provider unavailable')}</span><div><strong>Admin account</strong><small>Creator details unavailable</small></div><div><b className={`inviteBadge badge-${current}`}>{current}</b><small>{statusDetail(invite, current)}</small></div><span>{used} / {max > 0 ? max : ''}</span><div><strong>{expires ? formatDate(expires) : 'No expiration'}</strong><small>{expires ? relative(expires) : 'No expiration'}</small></div><div><strong>{created ? formatDate(created) : 'Unknown'}</strong><small>{created ? formatTime(created) : ''}</small></div><div className="inviteActions"><button aria-label={`View invitation ${label}`} onClick={() => onMessage(`${label}: ${current}, ${used} of ${max || 'unlimited'} uses`)}></button><button disabled aria-label="Edit invitation"></button><button className="dangerButton" disabled aria-label="Delete invitation"></button></div></div>; }
function invitationStatus(invite: Row) { const status = String(invite.status ?? 'inactive'); const expires = invite.expires_at ? Date.parse(String(invite.expires_at)) : 0; const used = Number(invite.redeemed_count ?? 0); const max = Number(invite.maximum_devices ?? 0); if (status === 'revoked') return 'inactive'; if (expires && expires <= Date.now()) return 'expired'; if (max > 0 && used >= max) return 'exhausted'; if (used > 0) return 'redeemed'; return status === 'active' ? 'active' : status; }
function statusDetail(invite: Row, status: string) { const used = Number(invite.redeemed_count ?? 0); const max = Number(invite.maximum_devices ?? 0); if (status === 'active') return max > 0 ? `${Math.max(max - used, 0)} uses remaining` : 'Awaiting redemption'; if (status === 'redeemed') return `Redeemed ${used} time${used === 1 ? '' : 's'}`; if (status === 'exhausted') return 'Maximum uses reached'; if (status === 'expired') return 'Expired'; return 'Not yet used'; }
function formatDate(value: string) { const time = Date.parse(value); return Number.isFinite(time) ? new Date(time).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' }) : 'Unknown'; }
function formatTime(value: string) { const time = Date.parse(value); return Number.isFinite(time) ? new Date(time).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : ''; }
function relative(value: string) { const time = Date.parse(value); if (!Number.isFinite(time)) return 'Unknown'; const hours = Math.ceil((time - Date.now()) / 3600000); if (hours > 24) return `in ${Math.ceil(hours / 24)} days`; if (hours > 0) return `in ${hours} hours`; return 'Expired'; }
