import { useEffect, useState } from 'react';
import { adminRequest } from './pairing';
import { diagnosticEventLabel, diagnosticStatusLabel, diagnosticTone, formatDiagnosticDuration } from './diagnosticsPresentation';

type Row = Record<string, any>;
type DiagnosticsData = { summary?: Row; devices?: Row[]; events?: Row[] };

export function AdminDiagnostics({ token }: { token: string; onMessage?: (message: string) => void }) {
  const [data, setData] = useState<DiagnosticsData | null>(null);
  const [hours, setHours] = useState('24');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedDevice, setSelectedDevice] = useState<Row | null>(null);
  const [logFilter, setLogFilter] = useState('ALL');
  const load = async () => { setLoading(true); setError(''); try { setData(await adminRequest(`admin-diagnostics?hours=${hours}`, token)); } catch { setError('Diagnostics data could not be loaded. Check the diagnostics service and try again.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [token, hours]);
  const summary = data?.summary ?? {};
  const devices = data?.devices ?? [];
  const metrics = [['TOTAL TESTERS', summary.totalDevices], ['HEALTHY', summary.healthy], ['NEEDS ATTENTION', Number(summary.degraded ?? 0) + Number(summary.activePlaybackIssues ?? 0)], ['OFFLINE', summary.offline], ['PLAYBACK ISSUES', summary.activePlaybackIssues]];
  return <div className="diagnosticsPage"><div className="diagnosticsToolbar"><div><span className="diagnosticsEyebrow">BETA SUPPORT</span><strong>Device Diagnostics Center</strong><small>Human-readable health and playback signals for tester support.</small></div><select value={hours} onChange={(event) => setHours(event.target.value)} aria-label="Diagnostics time range"><option value="1">Last hour</option><option value="24">Last 24 hours</option><option value="168">Last 7 days</option></select><button onClick={() => void load()} disabled={loading}>{loading ? 'Refreshing' : 'Refresh'}</button></div>{error ? <div className="diagnosticsError" role="alert">{error}<button onClick={() => void load()}>Retry</button></div> : null}{loading && !data ? <div className="diagnosticEmpty">Loading support diagnostics…</div> : null}{!loading || data ? <><div className="diagnosticMetricGrid">{metrics.map(([label, value]) => <article className="diagnosticMetric" key={String(label)}><small>{label}</small><strong>{value ?? 0}</strong></article>)}</div><section className="diagnosticPanel"><header><div><span className="diagnosticsEyebrow">DEVICE OVERVIEW</span><h2>Tester health</h2></div><span>{devices.length} testers</span></header><div className="diagnosticDeviceGrid">{devices.length ? devices.map((device, index) => <DeviceCard key={device.publicDeviceCode ?? index} device={device} onSelect={() => setSelectedDevice(device)} />) : <p className="diagnosticEmpty">No diagnostic-safe health records have arrived yet.</p>}</div>{selectedDevice ? <SupportLog device={selectedDevice} filter={logFilter} setFilter={setLogFilter} token={token} /> : null}</section><section className="diagnosticPanel"><header><div><span className="diagnosticsEyebrow">ENGINEERING DETAIL</span><h2>Recent activity</h2></div></header><details className="diagnosticTechnical"><summary>Technical details</summary>{(data?.events ?? []).slice(0, 30).map((event, index) => <div className="diagnosticEvent" key={event.id ?? index}><strong>{diagnosticEventLabel(event.event_type)}</strong><span>{event.error_code ?? event.metadata?.contentTitle ?? 'No additional detail'}<small>{event.event_type}</small></span><time>{event.event_at ? new Date(event.event_at).toLocaleString() : 'Not enough data yet'}</time></div>)}</details></section></> : null}</div>;
}

function DeviceCard({ device, onSelect }: { device: Row; onSelect: () => void }) {
  const playback = device.recentPlayback ?? {};
  return <article className="diagnosticDeviceCard" tabIndex={0} onClick={onSelect} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onSelect(); }}><header><div><strong>{device.assignedTesterName || device.friendlyName || 'Unassigned tester'}</strong><span>{device.publicDeviceCode ?? 'Device ID unavailable'}</span><small>{[device.manufacturer, device.model].filter(Boolean).join(' ') || 'Model not reported'}</small></div><b className={`diagnosticStatus ${diagnosticTone(device.overallStatus)}`}>{device.overallStatus ?? 'UNKNOWN'}</b></header><div className="diagnosticIndicators">{[['INTERNET', device.internet], ['PROVIDER', device.providerStatus], ['PLAYBACK', device.playbackStatus]].map(([label, value]) => <div key={String(label)}><span>{label}</span><strong className={`diagnosticIndicator ${diagnosticTone(value)}`}>{diagnosticStatusLabel(value)}</strong></div>)}</div><div className="diagnosticPlayback"><span>Provider <b>{device.providerName ?? 'Not enough data yet'}</b></span><span>Last played <b>{playback.contentTitle ?? 'Not enough data yet'}</b></span><span>Started in <b>{formatDiagnosticDuration(playback.timeToFirstFrameMs)}</b></span><span>Buffers <b>{playback.bufferCount ?? 0}</b></span></div><div className="diagnosticCause"><small>LIKELY ISSUE</small><strong>{String(device.likelyCause ?? 'UNKNOWN').replaceAll('_', ' ')}</strong><p>{device.likelyCauseExplanation ?? 'Not enough data yet'}</p></div></article>;
}

function SupportLog({ device, filter, setFilter, token }: { device: Row; filter: string; setFilter: (value: string) => void; token: string }) {
  const logs = (device.supportLogs ?? []).filter((entry: Row) => filter === 'ALL' || (filter === 'ERRORS' && entry.level === 'error') || (filter === 'WARNINGS' && entry.level === 'warning') || entry.category === filter.toLowerCase());
  const copyReport = () => { const playback = device.recentPlayback ?? {}; const report = ['NovaCast Beta Support Report', '', `Tester: ${device.assignedTesterName ?? 'Unknown'}`, `Device: ${device.publicDeviceCode ?? 'Unknown'}`, `Hardware: ${[device.manufacturer, device.model].filter(Boolean).join(' ') || 'Unknown'}`, `NovaCast: ${device.appVersion ?? 'Unknown'} (${device.appBuild ?? 'Unknown'})`, '', `Status: ${device.overallStatus ?? 'Unknown'}`, `Internet: ${diagnosticStatusLabel(device.internet)}`, `Provider: ${diagnosticStatusLabel(device.providerStatus)}`, `Playback: ${diagnosticStatusLabel(device.playbackStatus)}`, '', `Last content: ${playback.contentTitle ?? 'None recorded'}`, `Startup: ${formatDiagnosticDuration(playback.timeToFirstFrameMs)}`, `Buffers: ${playback.bufferCount ?? 0}`, '', `Likely issue: ${device.likelyCauseExplanation ?? 'No active issue detected'}`, `Recent errors: ${device.recentError?.message ?? 'None'}`].join('\n'); void navigator.clipboard?.writeText(report); };
  const sendCapture = async (action: 'start_diagnostics_capture' | 'stop_diagnostics_capture') => { await adminRequest('admin-device-action', token, { method: 'POST', body: JSON.stringify({ deviceId: device.publicDeviceCode, action }) }); };
  return <div className="diagnosticSupportLog"><header><div><span className="diagnosticsEyebrow">SUPPORT LOG</span><h3>{device.publicDeviceCode ?? 'Selected device'} timeline</h3></div><div className="diagnosticLogActions"><button onClick={copyReport}>Copy support report</button><button onClick={() => void sendCapture('start_diagnostics_capture')}>Start 15-minute capture</button><button onClick={() => void sendCapture('stop_diagnostics_capture')}>Stop capture</button></div></header><div className="diagnosticLogFilters">{['ALL', 'ERRORS', 'WARNINGS', 'PLAYBACK', 'NETWORK', 'PROVIDER', 'APP'].map((value) => <button className={filter === value ? 'selected' : ''} key={value} onClick={() => setFilter(value)}>{value}</button>)}</div>{logs.slice(0, 100).map((entry: Row, index: number) => <div className="diagnosticLogEntry" key={entry.id ?? index}><time>{entry.logged_at ? new Date(entry.logged_at).toLocaleTimeString() : '—'}</time><span><b>{String(entry.category ?? 'app').toUpperCase()}</b>{entry.message ?? 'Diagnostic event'}<small>{entry.context?.contentTitle ?? ''}</small></span><strong className={`diagnosticLogLevel ${entry.level}`}>{entry.level}</strong></div>)}{!logs.length ? <p className="diagnosticEmpty">No support log entries in this filter.</p> : null}</div>;
}
