export const novaTheme = {
  scheme: 'dark' as 'dark' | 'light',
  colors: {
    background: '#07090D',
    backgroundRaised: '#0B0F16',
    surface: '#11151C',
    surfaceMuted: '#171D25',
    surfaceFocused: '#1C2D49',
    accent: '#3B82F6',
    accentHover: '#61A5FF',
    focusRing: '#83B4FF',
    onAccent: '#FFFFFF',
    textPrimary: '#FFFFFF',
    textSecondary: '#9CA8B7',
    textMuted: '#687386',
    borderSubtle: 'rgba(255,255,255,0.08)',
    borderStrong: 'rgba(255,255,255,0.16)',
    success: '#33D39A',
    warning: '#FFB86A',
    danger: '#FF6B7A',
  },
  safeArea: {
    top: 34,
    right: 54,
    bottom: 34,
    left: 54,
  },
  layout: {
    navMinWidth: 164,
    navMaxWidth: 196,
    headerHeight: 70,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 22,
    xl: 30,
    xxl: 42,
  },
  typography: {
    logo: 32,
    pageTitle: 34,
    pageSubtitle: 16,
    sectionTitle: 23,
    cardTitle: 20,
    cardBody: 16,
    meta: 13,
    nav: 17,
    button: 17,
    code: 42,
    families: {
      display: 'sans-serif',
      body: 'sans-serif',
      mono: 'monospace',
    },
  },
  density: {
    pagePadding: 12,
    sectionGap: 10,
    rowHeight: 44,
    compactControlHeight: 36,
    scopeTabHeight: 34,
    artworkGap: 8,
    dividerOpacity: 0.08,
    focusGlowOpacity: 0.42,
    panelRadius: 10,
    cardRadius: 8,
    modalRadius: 12,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 22,
  },
  glow: {
    focusShadowOpacity: 0.35,
    focusShadowRadius: 12,
    borderWidth: 2,
  },
  motion: {
    fast: 140,
    normal: 170,
    slow: 240,
  },
} as const;

export type NovaTheme = typeof novaTheme;
